spring:
#  r2dbc:
#    url: r2dbc:postgresql://54.180.176.187:5432/ktgame_database
#    username: ktgame
#    password: ktgame
  data:
    mongodb:
      host: 54.180.176.187
      port: 27017
      database: good_game
    redis:
      host: 54.180.176.187
      port: 6379
logging:
  level:
    root: debug
